networks:
  face-expression-network:
    driver: bridge

volumes:
  sqlite_data:
services:
  builder:
    build:
      context: .
    image: face-expression:latest
    profiles:
      - build

  backend:
    image: face-expression:latest
    env_file: ".env"
    container_name: face-expression-backend
    command: app
    ports:
      # - "${BACKEND_PORT:-9009}:9000"
      - 9009:9000
    volumes:
      - ./:/code
    networks:
      - face-expression-network